In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [51]:
df_clean = pd.read_csv('../data/processed/card_profiler_clean.csv')

In [52]:
df_clean.drop(columns=["Unnamed: 0"], inplace=True)

columns_with_num = df_clean.select_dtypes(include='number').columns

In [53]:
df_prepare_clustering = df_clean[columns_with_num].copy()

def log1p(df, columns):
    for i in columns:
        df[f"{i}_log"] = np.log1p(df[i])
        df.drop(columns=i, inplace=True)

log1p(df_prepare_clustering, columns_with_num)

In [54]:
df_prepare_clustering.head(5)

,BALANCE_log,PURCHASES_log,ONEOFF_PURCHASES_log,INSTALLMENTS_PURCHASES_log,CASH_ADVANCE_log,CREDIT_LIMIT_log,PAYMENTS_log
0,3.735304,4.568506,0.000000,4.568506,0.000000,6.908755,5.312231
1,8.071989,0.000000,0.000000,0.000000,8.770896,8.853808,8.319725
2,7.822504,6.651791,6.651791,0.000000,0.000000,8.922792,6.434654
3,7.419183,7.313220,7.313220,0.000000,5.331694,8.922792,0.000000
4,6.707735,2.833213,2.833213,0.000000,0.000000,7.090910,6.521114

In [55]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_prepare_clustering)

In [58]:
df_scaled = pd.DataFrame(df_scaled, columns=df_prepare_clustering.columns, index=df_prepare_clustering.index)

In [59]:
df_scaled.head(5)

,BALANCE_log,PURCHASES_log,ONEOFF_PURCHASES_log,INSTALLMENTS_PURCHASES_log,CASH_ADVANCE_log,CREDIT_LIMIT_log,PAYMENTS_log
0,-1.205498,-0.113732,-0.987198,0.394362,-0.930636,-1.447095,-0.825080
1,0.948821,-1.680213,-0.987198,-1.087586,1.528788,0.925997,1.065109
2,0.824885,0.600600,1.061910,-1.087586,-0.930636,1.010161,-0.119646
3,0.624529,0.827395,1.265665,-1.087586,0.564410,1.010161,-4.163779
4,0.271106,-0.708741,-0.114417,-1.087586,-0.930636,-1.224854,-0.065306

In [61]:
df_scaled.describe()

,BALANCE_log,PURCHASES_log,ONEOFF_PURCHASES_log,INSTALLMENTS_PURCHASES_log,CASH_ADVANCE_log,CREDIT_LIMIT_log,PAYMENTS_log
count,8.949000e+03,8.949000e+03,8.949000e+03,8.949000e+03,8.949000e+03,8.949000e+03,8.949000e+03
mean,1.270386e-16,6.351930e-17,-7.622316e-17,4.128754e-17,2.540772e-17,3.557081e-16,-2.540772e-17
std,1.000056e+00,1.000056e+00,1.000056e+00,1.000056e+00,1.000056e+00,1.000056e+00,1.000056e+00
min,-3.061071e+00,-1.680213e+00,-9.871985e-01,-1.087586e+00,-9.306359e-01,-5.079142e+00,-4.163779e+00
25%,-6.454735e-01,-4.085542e-01,-9.871985e-01,-1.087586e+00,-9.306359e-01,-8.741168e-01,-4.233803e-01
50%,3.039534e-01,3.404191e-01,1.413749e-01,3.720783e-01,-9.306359e-01,-1.075291e-01,8.148696e-02
75%,7.283677e-01,7.245116e-01,9.723332e-01,9.080179e-01,1.036840e+00,8.355939e-01,5.818495e-01
max,1.834319e+00,2.023105e+00,2.282948e+00,2.163164e+00,2.086782e+00,2.701408e+00,2.645391e+00